theme = "noir256_light"

[editor]
true-color = true
cursorline = true

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]
mode.normal = "nor"
mode.insert = "-- INSERT --"
mode.select = "-- SELECT --"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
# normal = "block"
# select = "underline"

[editor.whitespace.render]
newline = "all"

[editor.indent-guides]
render = true
character = "▏"

[editor.gutters.line-numbers]
min-width = 1

# unselects selecton and removes additional cursors with esc
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
