# The structure is based on `autumn` by Jens Getreu.
# This color scheme is inspired by 'vim-256noir' by Andreas van Cranenburgh

"ui.background" = { }
"ui.menu" = { fg = "my_white", bg = "my_gray2" }
"ui.menu.selected" = { fg = "my_gray2", bg = "my_gray5" }
"ui.linenr" = { fg = "my_gray4"}
"ui.popup" = { bg = "my_gray2" }
"ui.window" = { fg = "my_gray3", bg = "my_gray2" }
"ui.linenr.selected" = { fg = "my_gray6", bg = "my_gray0"}
"ui.selection" = { bg = "my_gray3" }
"comment" = { fg = "my_comment", modifiers = ["italic"] }
"ui.cursorline" = { bg = "my_gray3" }
"ui.statusline" = { fg = "my_gray6", bg = "my_gray2" }
"ui.statusline.inactive" = { fg = 'my_gray4', bg = 'my_gray2' }
"ui.statusline.insert" = {fg = "my_black", bg = "my_gray5", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "my_gray6", bg = "my_gray2"}
"ui.statusline.select" = {fg = "my_gray6", bg = "my_black", modifiers = ["bold"]}
"ui.cursor" = { fg = "my_gray5", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "my_white", modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "my_black" }
"ui.cursorline.secondary" = { bg = "my_black" }
"ui.text" = "my_white"
"operator" = "my_white"
"ui.text.focus" = "my_white"
"variable" = "my_white3"
"constant.numeric" = "my_turquoise2"
"constant" = "my_white3"
"attribute" = "my_turquoise"
"type" = { fg = "my_white3", modifiers = ["italic"] }
"ui.cursor.match" = { fg = "my_white3", modifiers = ["underlined"] }
"string"  = "my_green"
"variable.other.member" = "my_brown"
"constant.character.escape" = "my_turquoise"
"function" = "my_yellow1"
"constructor" = "my_yellow1"
"special" = "my_yellow1"
"keyword" = "my_red"
"label" = "my_red"
"namespace" = "my_white3"
"ui.help" = { fg = "my_gray6", bg = "my_gray2" }
"ui.virtual.whitespace" = { fg = "my_gray5" }
"ui.virtual.ruler" = { bg = "my_gray1" }
"punctuation" = "my_darkgray"

"markup.heading" = "my_yellow1"
"markup.list" = "my_white2"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = {  modifiers = ["italic"] }
"markup.link.url" = "my_turquoise2"
"markup.link.text" = "my_white2"
"markup.quote" = "my_brown"
"markup.raw" = "my_green"

"diff.plus" = "my_green"
"diff.delta" = "my_white"
"diff.minus" = "my_red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { }
"hint" = "my_gray5"
"debug" = "my_yellow2"
"info" = "my_yellow2"
"warning" = "my_yellow2"
"error" = "my_red"

[palette]
my_black      = "#ffffff" # Cursorline
my_gray0      = "#fafafa" # Default Background
my_gray1      = "#eeeeee" # Ruler
my_gray2      = "#eeeeee" # Lighter Background (Used for status bars and folding marks)
my_gray3      = "#ebe6e6" # Selection Background
my_gray4      = "#c1c1c1" # Invisibles, Line Highlighting, Line Numbers
my_comment    = "#a9a9a9" # Comments
my_gray5      = "#d4d4d4" # Dark Foreground (Used for status bars)
my_gray6      = "#383838" # Light Foreground (Not often used)
my_gray7      = "#e0e0e0" # Light Background (Not often used)
my_white      = "#000000" # Default Foreground, Caret, Delimiters, Operators
my_white2     = "#0000ff" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
my_white3     = "#909090" # Classes, Markup Bold, Search Text Background
my_turquoise  = "#9e9e9e" # Support, Regular Expressions, Escape Characters
my_turquoise2 = "#ef0000" # URL, constants
my_green      = "#4c4c4c" # Strings, Inherited Class, Markup Code, Diff Inserted
my_brown      = "#696969" # Member variables, Quotes
my_yellow1    = "#000000" # Functions, Methods, Attribute IDs, Headings
my_yellow2    = "#808080" # Debug, Info
my_red        = "#000000" # Keywords, Storage, Selector, Diff Changed
my_darkgray   = "#9d9d9d" # Punctuation (delimiter, brackets etc)
