# The structure is based on `autumn` by Jens Getreu.
# This color scheme is inspired by 'vimr-256noir' by Andreas van Cranenburgh

"ui.background" = { bg = "bg0" }
"ui.menu" = { fg = "fg1", bg = "bg1" }
"ui.menu.selected" = { fg = "bg1", bg = "gray2" }
"ui.linenr" = { fg = "gray2", bg = "bg0" }
"ui.popup" = { bg = "bg1" }
"ui.window" = { fg = "gray2", bg = "bg1" }
"ui.linenr.selected" = { fg = "fg1", bg = "bg0"}
"ui.selection" = { bg = "gray2" }
"comment" = { fg = "gray1", modifiers = ["italic"] }
"ui.cursorline" = { bg = "gray2" }
"ui.statusline" = { fg = "fg1", bg = "bg1" }
"ui.statusline.inactive" = { fg = 'dark_gray', bg = 'bg1' }
"ui.statusline.insert" = {fg = "light_black", bg = "gray2", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "fg1", bg = "bg1"}
"ui.statusline.select" = {fg = "fg1", bg = "light_black", modifiers = ["bold"]}
"ui.cursor" = { fg = "gray2", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "fg0", modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "light_black" }
"ui.cursorline.secondary" = { bg = "light_black" }
"ui.text" = "fg1"
"operator" = "gray0"
"ui.text.focus" = "fg1"
"variable" = "white0"
"constant.numeric" = "red0"
"constant" = "white0"
"attribute" = "red0"
"type" = { fg = "white0", modifiers = ["italic"] }
"ui.cursor.match" = { fg = "white0", modifiers = ["underlined"] }
"string"  = "white1"
"variable.other.member" = "white4"
"constant.character.escape" = "gray1"
"function" = "white2"
"constructor" = "white2"
"special" = "white2"
"keyword" = { fg = "white3", modifiers = ["bold"] }
"label" = "white3"
"namespace" = "white0"
"ui.help" = { fg = "fg1", bg = "bg1" }
"ui.virtual.whitespace" = { fg = "gray2" }
"ui.virtual.ruler" = { bg = "light_black" }
"punctuation" = "gray3"

"markup.heading" = "white2"
"markup.list" = "fg1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = {  modifiers = ["italic"] }
"markup.link.url" = "red0"
"markup.link.text" = "fg0"
"markup.quote" = "white4"
"markup.raw" = "white1"

"diff.plus" = "white1"
"diff.delta" = "fg0"
"diff.minus" = "red0"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "bg0" }
"hint" = "gray2"
"debug" = "yellow0"
"info" = "yellow0"
"warning" = "yellow0"
"error" = "red0"

[palette]
bg0         = "#000000" # default background
bg1         = "#181818" # lighter background (status bars, folding marks)

light_black = "#151515" # cursorline, ruler

gray0       = "#757575" # operators
gray1       = "#666666" # comments, escape characters
gray2       = "#363636" # line numbers, selection, windows, whitespaces, hints
gray3       = "#545454" # punctuation 

fg0         = "#ffffff" # cursor and diff.delta
fg1         = "#cccccc" # default foreground

yellow0     = "#f0e200" # debug, info, warnings
red0        = "#eb0000" # constant numbers

white0      = "#adadad" # variables, constants, types, namespaces, search text background 
white1      = "#737373" # strings, diff.plus
white2      = "#f7f7f7" # functions, constructors
white3      = "#d9d9d9" # keywords, labels
white4      = "#d6d6d6" # member variables
