# The structure is based on `autumn` by Jens Getreu.
# This color scheme is inspired by 'vimr-256noir' by Andreas van Cranenburgh

"ui.background" = { bg = "bg0" }
"ui.menu" = { fg = "fg1", bg = "bg1" }
"ui.menu.selected" = { fg = "bg1", bg = "gray0" }
"ui.linenr" = { fg = "gray0", bg = "bg0" }
"ui.popup" = { bg = "bg1" }
"ui.window" = { fg = "gray0", bg = "bg1" }
"ui.linenr.selected" = { fg = "fg1", bg = "bg0"}
"ui.selection" = { bg = "gray0" }
"comment" = { fg = "gray1", modifiers = ["italic"] }
"ui.cursorline" = { bg = "gray0" }
"ui.statusline" = { fg = "fg1", bg = "bg1" }
"ui.statusline.inactive" = { fg = 'dark_gray', bg = 'bg1' }
"ui.statusline.insert" = {fg = "light_black", bg = "gray0", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "fg1", bg = "bg1"}
"ui.statusline.select" = {fg = "fg1", bg = "light_black", modifiers = ["bold"]}
"ui.cursor" = { fg = "gray0", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "fg0", modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "light_black" }
"ui.cursorline.secondary" = { bg = "light_black" }
"ui.text" = "fg1"
"operator" = "gray3"
"ui.text.focus" = "fg1"
"variable" = "white2"
"constant.numeric" = "red0"
"constant" = "white2"
"attribute" = "red0"
"type" = { fg = "white2", modifiers = ["italic"] }
"ui.cursor.match" = { fg = "white2", modifiers = ["bold", "slow_blink"] }
"string"  = "white3"
"variable.other.member" = "white0"
"constant.character.escape" = "gray1"
"function" = "white4"
"constructor" = "white4"
"special" = "white4"
"keyword" = { fg = "white1", modifiers = ["bold"] }
"label" = "white1"
"namespace" = "white2"
"ui.help" = { fg = "fg1", bg = "bg1" }
"ui.virtual.whitespace" = { fg = "gray0" }
"ui.virtual.ruler" = { bg = "light_black" }
# "ui.virtual.jump-label" = { fg = "white2", modifiers = ["reversed"] }
"ui.virtual.jump-label" = { fg = "fg0", modifiers = ["bold", "italic"] }
"punctuation" = "gray2"

"markup.heading" = "white4"
"markup.list" = "fg1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = {  modifiers = ["italic"] }
"markup.link.url" = "white2"
"markup.link.text" = "fg0"
"markup.quote" = "white0"
"markup.raw" = "white3"

"diff.plus" = "white3"
"diff.delta" = "fg0"
"diff.minus" = "red0"

"diagnostic" = { underline = {color="red0", style="curl"}}
"ui.gutter" = { bg = "bg0" }
"hint" = "gray0"
"debug" = "yellow0"
"info" = "yellow0"
"warning" = "yellow0"
"error" = "red0"

[palette]
bg0         = "#000000" # default background
bg1         = "#181818" # lighter background (status bars, folding marks)

light_black = "#151515" # cursorline, ruler

gray0       = "#363636" # line numbers, selection, windows, whitespaces, hints
gray1       = "#666666" # comments, escape characters
gray2       = "#545454" # punctuation 
gray3       = "#757575" # operators

fg0         = "#ffffff" # cursor and diff.delta
fg1         = "#cccccc" # default foreground

yellow0     = "#f0e200" # debug, info, warnings
red0        = "#eb0000" # constant numbers

white_4      = "#f7f7f7" # functions, constructors
white_0      = "#d6d6d6" # member variables
white_1      = "#d9d9d9" # keywords, labels
white_2      = "#adadad" # variables, constants, types, namespaces, search text background 
white_3      = "#737373" # strings, diff.plus
